version: '3'
services:
  # React App Service
  react-app:
    image: pouzani/react-voiture:1.0
    ports:
      - "3000:3000"

  # Spring Boot App Service
  spring-app:
    image: pouzani/spring-voiture:2.3
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - my-network

  # MySQL Service
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fullstack
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    ports:
      - "3306:3306"
    networks:
      - my-network

networks:
  my-network:
